[versions]
junit = "5.7.0"

[libraries]
kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

[bundles]

